services:
  backend:
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  frontend:
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=https://agente-ai.hospitalevangelico.com.br/api/v1
      - NEXT_PUBLIC_API_URL=https://agente-ai.hospitalevangelico.com.br/api/v1
    command: sh -c "pnpm build && pnpm start"
